[run]
build = "npm run predeploy"
test = "npm run test"
lint = "npm run lint"

[paths]
base = "./build"  # base directory to operate in (for monorepos)
src = "./src"        # source directory (under the base directory) from which context will be retrieved

[gptengineer-app]  # this namespace is used for gptengineer.app
project_id = "cea1b28d-2d7b-400e-a849-0ff8e2bf7b23"


