[run]
build = "npm run build"
test = "npm run test"
lint = "npm run lint"

[paths]
base = "./build"  # base directory to operate in (for monorepos)
src = "./src"        # source directory (under the base directory) from which context will be retrieved

[gptengineer-app]  # this namespace is used for gptengineer.app, we can use this for internal experiments
project_id = "690f769d-2f81-4cfa-baf1-e625927228c6"